[project]
name = "retro-pixel-font"
version = "0.0.0"
requires-python = ">=3.14"

dependencies = [
    "pixel-font-builder==0.0.41",
    "pixel-font-knife==0.0.19",
    "pillow==12.0.0",
    "beautifulsoup4==4.14.2",
    "jinja2==3.1.6",
    "loguru==0.7.3",
]
